### ISSUE TITLE
Configure/enable metrics server through yaml config

### ISSUE THREAD

**Issue by FiV0** [xtdb/crux#3469]
Currently something like
```yaml
txLog: !Local
  path: /tmp/test-log
storage: !Local
  path: /tmp/test-storage
  maxCacheEntries: 1025
metrics:
```
does not start the metrics server.
