### ISSUE TITLE
Support `SET ROLE NONE`

### ISSUE THREAD

**Issue by Akeboshiwind** [xtdb/crux#3745]
`SET ROLE = 'NONE'` is currently valid, but `SET ROLE NONE` is not.

`metabase-enterprise` throws this error when scanning the database as well as when running an ordinary query:
```
ERROR: Errors parsing SQL statement: - line 1:9 mismatched input 'NONE' expecting {'=', 'TO'}
```

<details><summary>To (roughly) reproduce:</summary>

```yaml
services:
  xtdb:
    image: ghcr.io/xtdb/xtdb:nightly
    hostname: xtdb
    ports:
      - '5432:5432'

  metabase:
    image: metabase/metabase-enterprise
    restart: unless-stopped
    environment:
      MB_PREMIUM_EMBEDDING_TOKEN: <your token> (not sure if required for reproduction)
    depends_on:
      - xtdb
    ports:
      - '3003:3000'
```

Setup xtdb using `xtdb` as the hostname then try to scan or run `SELECT * FROM xt.txs` or something.

</details>
