### ISSUE TITLE
Authentication in XTDB

### ISSUE THREAD

**Issue by FiV0** [xtdb/crux#3852]
The user provides something similar to the following in the startup config (which is loosly inspired by pg_hba.conf https://www.postgresql.org/docs/current/auth-pg-hba-conf.html)  

```yaml
modules:
- !HttpServer
  port: 3000
  authn: !AuthnSettings
    - !AuthnRecord
    type: LOCAL 
    user: all
    method: TRUST 

    - !AuthnRecord
    type: HOST 
    user: all
    address: 127.0.0.1/32
    method: PASSWORD 
``` 
at startup.

- The inital user is only `{:user "xtdb" :password "xtdb"}`
- psql connections can work as PG does 
- client addr + pg_hba for trust/password + user kept on the connection
- HTTP server, likewise - HTTP 'basic' authentication supported for now
    - in both above cases we add the `current user` to the API requests
- in-process API defaults `current-user` to be `xtdb` (whatever access/perms that might have at that point)
Options:
   1. supply `current-user` nil explicitly - i.e. differentiate between nil and not provided -  `TxOptions` need to be refactored out
   2. `xtdb.api` defaults it to `current-user` `xtdb` , HTTP and pgwire call `xtp/q` and `xtp/submit-tx` instead
- Clojure API trusts `current-user` to have been authenticated if necessary
