### ISSUE TITLE
Migration tool for beta7

### ISSUE THREAD

**Issue by jarohen** [xtdb/crux#4176]
We should provide a migration tool for users migrating their data to beta7.

If users have the full history of their database in the log still (either through infinite retention, or maybe they're deriving the XT log from another upstream log) it may be easier for them to simply replay - i.e. remove the contents of the object store - but an infinite retention log is no longer a hard requirement, so we should provide a tool to migrate users' object stores.

Migration process could be as follows:

* User runs a one-shot task while the beta6 nodes are still up
* Task copies over L0 files and block files (see below)
* Task notifies the user that the migration is complete and exits.
* User performs a green/blue migration of their XT nodes from beta6 -> beta7 in the usual way
* beta7 compactors compact L0 files as normal
* Later, user cleans up `/v05` from their object store.

As for the tool:

* Connect to the user's object store.
* For each block-metadata transit/json file in `/v05/blocks`
  * create a chunk-idx -> block-idx mapping
  * for each table:
    * copy L0 files over, renaming as appropriate (`l00-b04.arrow`)
      * ~this should only need a rename, because L0 file contents are unchanged~ no, because 97940ac3 and #4014 
    * create table-block files (see #4171)
  * create block file.
* Log a message to the user letting them know that:
  * the migration has finished successfully
  * they can now scale up the new nodes and scale down the old ones in the normal green/blue manner.

**Comment by jarohen** [comment]
Thought dump re impl (non-normative):

* Run using the same Docker image as the nodes themselves - this is so that it can use the same Docker configuration (env vars etc)
* I would imagine that the user would override the Docker CMD, e.g. `--migrate-from v05` - at which point xtdb.cli would switch into migration mode
* Don't worry about making this part too general - I'd guess we'll remove this code in beta8.

We opted not to replay from a log for this migration given that the L0 files are remaining unchanged (in content). Replaying from a log using a different projection is generally safer (indeed, we've done that throughout V1) but in this case, with the L0 files not changing and the fact that a replay would have to sort them in system-time order, we decided to go for a transformation instead.

**Comment by refset** [comment]
According to an LLM, we could also consider providing this as a Helm pre-upgrade hook...

----

A **Helm upgrade** can be leveraged to assist with this migration process by incorporating the migration tool as a Helm **pre-upgrade hook** or as a **Job** that runs before the new nodes come online. Here's how it could work:

### **1. Helm Pre-Upgrade Hook for One-Shot Migration**
Helm allows defining **hooks** that run before, during, or after upgrades. A **pre-upgrade** hook can ensure that the migration is performed before the new `beta7` XTDB nodes come up.

- **Define a Kubernetes Job** in your Helm chart that runs before the upgrade.
- This Job will:
  - Connect to the object store.
  - Copy over `L0` files and block files.
  - Generate table-block files as needed.
  - Log completion and notify the user.

Example `Job` YAML in Helm:
```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: xtdb-migration-job
  annotations:
    "helm.sh/hook": pre-upgrade
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: migration-tool
          image: xtdb-migration:latest  # Your migration tool container
          command: ["./migrate.sh"]
          env:
            - name: XTDB_OBJECT_STORE
              value: "s3://my-bucket/xtdb"
```
This ensures that the migration happens **before** `beta7` nodes start.

---

### **2. Helm Upgrade for Green/Blue Deployment**
Once the migration completes, the Helm upgrade can proceed normally:

- **Scale down `beta6` nodes gracefully.**
- **Deploy `beta7` nodes.**
- **Ensure compactors process L0 files post-upgrade.**
- **User later cleans up `/v05/` manually.**

This is a **safe, controlled way** to automate the migration and ensure users don’t accidentally upgrade without migrating their object store.
