### ISSUE TITLE
MinIO NPE at ListObjectsV2Response.isTruncated()

### ISSUE THREAD

**Issue by refset** [xtdb/crux#4201]
Reported in https://discuss.xtdb.com/t/s3-errors-for-2-0-0-beta6/568 with the following stacktrace

```
Attaching to xtdb
xtdb  | Starting XTDB 2.x @ 2.0.0-beta6 @ df55068 ...
xtdb  | 08:32:42 | INFO  xtdb.metrics | tagging all metrics with node-id: 3f75e770
xtdb  | {:clojure.main/message
xtdb  |  "Execution error (NullPointerException) at xtdb.aws.S3$listAllObjects0$1/invokeSuspend (S3.kt:202).\nCannot invoke \"java.lang.Boolean.booleanValue()\" because the return value of \"software.amazon.awssdk.services.s3.model.ListObjectsV2Response.isTruncated()\" is null\n",
xtdb  |  :clojure.main/triage
xtdb  |  {:clojure.error/class java.lang.NullPointerException,
xtdb  |   :clojure.error/line 202,
xtdb  |   :clojure.error/cause
xtdb  |   "Cannot invoke \"java.lang.Boolean.booleanValue()\" because the return value of \"software.amazon.awssdk.services.s3.model.ListObjectsV2Response.isTruncated()\" is null",
xtdb  |   :clojure.error/symbol xtdb.aws.S3$listAllObjects0$1/invokeSuspend,
xtdb  |   :clojure.error/source "S3.kt",
xtdb  |   :clojure.error/phase :execution},
xtdb  |  :clojure.main/trace
xtdb  |  {:via
xtdb  |   [{:type java.lang.NullPointerException,
xtdb  |     :message
xtdb  |     "Cannot invoke \"java.lang.Boolean.booleanValue()\" because the return value of \"software.amazon.awssdk.services.s3.model.ListObjectsV2Response.isTruncated()\" is null",
xtdb  |     :at [xtdb.aws.S3$listAllObjects0$1 invokeSuspend "S3.kt" 202]}],
xtdb  |   :trace
xtdb  |   [[xtdb.aws.S3$listAllObjects0$1 invokeSuspend "S3.kt" 202]
xtdb  |    [kotlin.coroutines.jvm.internal.BaseContinuationImpl
xtdb  |     resumeWith
xtdb  |     "ContinuationImpl.kt"
xtdb  |     33]
xtdb  |    [kotlin.sequences.SequenceBuilderIterator
xtdb  |     hasNext
xtdb  |     "SequenceBuilder.kt"
xtdb  |     129]
xtdb  |    [clojure.lang.RT chunkIteratorSeq "RT.java" 537]
xtdb  |    [clojure.lang.RT seqFrom "RT.java" 567]
xtdb  |    [clojure.lang.RT seq "RT.java" 557]
xtdb  |    [clojure.core$seq__5486 invokeStatic "core.clj" 139]
xtdb  |    [clojure.core$seq__5486 invoke "core.clj" 139]
xtdb  |    [xtdb.metadata$load_blocks_metadata invokeStatic "metadata.clj" 414]
xtdb  |    [xtdb.metadata$load_blocks_metadata invoke "metadata.clj" 412]
xtdb  |    [xtdb.metadata$eval19345$fn__19347 invoke "metadata.clj" 433]
xtdb  |    [clojure.lang.MultiFn invoke "MultiFn.java" 234]
xtdb  |    [integrant.core$try_build_action invokeStatic "core.cljc" 419]
xtdb  |    [integrant.core$try_build_action invoke "core.cljc" 418]
xtdb  |    [integrant.core$build_key invokeStatic "core.cljc" 427]
xtdb  |    [integrant.core$build_key invoke "core.cljc" 423]
xtdb  |    [clojure.core$partial$fn__5931 invoke "core.clj" 2656]
xtdb  |    [clojure.core.protocols$fn__8275 invokeStatic "protocols.clj" 167]
xtdb  |    [clojure.core.protocols$fn__8275 invoke "protocols.clj" 123]
xtdb  |    [clojure.core.protocols$fn__8229$G__8224__8238
xtdb  |     invoke
xtdb  |     "protocols.clj"
xtdb  |     19]
xtdb  |    [clojure.core.protocols$seq_reduce invokeStatic "protocols.clj" 31]
xtdb  |    [clojure.core.protocols$fn__8262 invokeStatic "protocols.clj" 74]
xtdb  |    [clojure.core.protocols$fn__8262 invoke "protocols.clj" 74]
xtdb  |    [clojure.core.protocols$fn__8203$G__8198__8216
xtdb  |     invoke
xtdb  |     "protocols.clj"
xtdb  |     13]
xtdb  |    [clojure.core$reduce invokeStatic "core.clj" 6965]
xtdb  |    [clojure.core$reduce invoke "core.clj" 6947]
xtdb  |    [integrant.core$build invokeStatic "core.cljc" 453]
xtdb  |    [integrant.core$build invoke "core.cljc" 430]
xtdb  |    [integrant.core$init invokeStatic "core.cljc" 675]
xtdb  |    [integrant.core$init invoke "core.cljc" 667]
xtdb  |    [integrant.core$init invokeStatic "core.cljc" 672]
xtdb  |    [integrant.core$init invoke "core.cljc" 667]
xtdb  |    [xtdb.node.impl$open_node invokeStatic "impl.clj" 272]
xtdb  |    [xtdb.node.impl$open_node invoke "impl.clj" 269]
xtdb  |    [clojure.lang.Var invoke "Var.java" 386]
xtdb  |    [xtdb.api.Xtdb$Config open "Xtdb.kt" 76]
xtdb  |    [xtdb.api.Xtdb$Companion openNode "Xtdb.kt" 103]
xtdb  |    [xtdb.api.Xtdb openNode "Xtdb.kt" -1]
xtdb  |    [xtdb.node$start_node invokeStatic "node.clj" 89]
xtdb  |    [xtdb.node$start_node invoke "node.clj" 69]
xtdb  |    [xtdb.cli$start_node_from_command_line invokeStatic "cli.clj" 106]
xtdb  |    [xtdb.cli$start_node_from_command_line invoke "cli.clj" 91]
xtdb  |    [clojure.lang.Var invoke "Var.java" 386]
xtdb  |    [xtdb.main$_main invokeStatic "main.clj" 17]
xtdb  |    [xtdb.main$_main doInvoke "main.clj" 5]
xtdb  |    [clojure.lang.RestFn applyTo "RestFn.java" 140]
xtdb  |    [clojure.lang.Var applyTo "Var.java" 707]
xtdb  |    [clojure.core$apply invokeStatic "core.clj" 667]
xtdb  |    [clojure.main$main_opt invokeStatic "main.clj" 515]
xtdb  |    [clojure.main$main_opt invoke "main.clj" 511]
xtdb  |    [clojure.main$main invokeStatic "main.clj" 665]
xtdb  |    [clojure.main$main doInvoke "main.clj" 617]
xtdb  |    [clojure.lang.RestFn applyTo "RestFn.java" 140]
xtdb  |    [clojure.lang.Var applyTo "Var.java" 707]
xtdb  |    [clojure.main main "main.java" 40]],
xtdb  |   :cause
xtdb  |   "Cannot invoke \"java.lang.Boolean.booleanValue()\" because the return value of \"software.amazon.awssdk.services.s3.model.ListObjectsV2Response.isTruncated()\" is null"}}
xtdb  |
xtdb  | Execution error (NullPointerException) at xtdb.aws.S3$listAllObjects0$1/invokeSuspend (S3.kt:202).
xtdb  | Cannot invoke "java.lang.Boolean.booleanValue()" because the return value of "software.amazon.awssdk.services.s3.model.ListObjectsV2Response.isTruncated()" is null
xtdb  |
xtdb exited with code 1
```

**Comment by tempire** [comment]
Is there any plan to address this?

Use case: I need to be able to run local database systems without depending on external systems, both for privacy and unecessary traffic costs.

I need dev, staging, production, and airgapped secure systems need to run the same stack, which requires the flexibility of cutting the cord from a cloud provider.

minio doesn't have the same method support (no isTruncated), but in most ways it's a drop in replacement. (before beta6, it worked fine)

https://minio-java.min.io/index.html?io/minio/ListObjectsV2Response.html

**Comment by refset** [comment]
Hi @tempire thanks for the nudge. We've not had others report seeing this also yet despite knowing that MinIO has been used elsewhere. Right now we haven't seen enough information about how to reproduce the issue to feel confident about investigating further.

Can you share more details about your setup and what was running when you saw the error?

**Comment by tempire** [comment]
Hmm. That is interesting. I'm not sure what is different about my set up, then - it seems pretty straightforward.

I'm running minio, redpanda, and xtdb, connected by docker networks. Before beta6, it worked without a hitch. It works fine when using aws s3 or local storage.

One strange thing to note is that even before beta6, even when the s3 endpoint is specified, xtdb prepends "xtdb." to the endpoint host when attempting to connect. Adding an alias to the minio docker resolution took care of that.

Included are the relevent portions of my configuration. Maybe you can see something obvious that I'm missing.

Loving 2.x, by the way. The sql ux is 😘

# xtdb.yaml

```
server:
  port: !Env XTDB_PSQL_PORT

log: !Kafka
  bootstrapServers: !Env KAFKA_BOOTSTRAP_SERVERS
  topic: "xtdb-log-topic"
  autoCreateTopic: true

healthz:
  port: 8080

modules:
- !HttpServer
  port: !Env XTDB_HTTP_PORT

storage: !Remote
  objectStore: !S3
    bucket: !Env XTDB_S3_BUCKET
    endpoint: !Env XTDB_S3_ENDPOINT
    credentials:
      accessKey: !Env AWS_ACCESS_KEY
      secretKey: !Env AWS_SECRET_KEY

  localDiskCache: "/var/cache/xtdb/remote-cache"

```

# xtdb docker-compose.yml

```
services:
  xtdb:
    container_name: xtdb
    image: ghcr.io/xtdb/xtdb-aws:2.0.0-beta9
    ports:
      - 5434:5432
    networks:
      - redpanda
      - minio
      - xtdb
    volumes:
      - xtdb-remote-cache:/var/cache/xtdb/remote-cache
      - xtdb-log:/var/lib/xtdb/log
      - ./xtdb.yaml:/xtdb.yaml
    command: ["env", "&&", "-f", "/xtdb.yaml"]
    env_file:
      .env

networks:
  xtdb:
    name: xtdb
  redpanda:
    external: true
  minio:
    external: true

volumes:
  xtdb-remote-cache:
  xtdb-log:
```

# xtdb .env

```
DOCKER_IMAGE=ghcr.io/xtdb/xtdb-aws:2.0.0-beta9

KAFKA_BOOTSTRAP_SERVERS=redpanda-0:9092,redpanda-1:9092,redpanda-2:9092
XTDB_LOG_TOPIC=xtdb-log
XTDB_LOGGING_LEVEL=TRACE
XTDB_HTTP_PORT=3000
XTDB_PSQL_PORT=5432

XTDB_S3_BUCKET=xtdb
XTDB_S3_ENDPOINT=http://minio:9000
AWS_ACCESS_KEY=minio
AWS_SECRET_KEY=ne7jei3aighahz5niiZaaifx4xaira
AWS_REGION=us-west-2
```

# minio docker-compose.yml

```
services:
  minio:
    hostname: minio
    container_name: minio
    image: minio/minio:RELEASE.2025-05-24T17-08-30Z
    restart: always
    ports:
      - 9000:9000
      - 8022:8022
      - 9001:9001
    networks:
      minio:
        aliases:
          - xtdb.minio
      traefik_default:
    volumes:
      - minio-quay:/data
    env_file:
      - .env
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

networks:
  minio:
    name: minio

volumes:
  minio-quay:
    driver: local
```

# minio .env
```
MINIO_ROOT_USER=minio
MINIO_ROOT_PASSWORD=ne7jei3aighahz5niiZaaifx4xaira
MINIO_HTTP_TRACE=/dev/stdout
```
